# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'card_bank.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(840, 600)
        self.mainGridWidget = QtGui.QWidget(MainWindow)
        self.mainGridWidget.setObjectName(_fromUtf8("mainGridWidget"))
        self.gridLayout_6 = QtGui.QGridLayout(self.mainGridWidget)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.stackedWidget = QtGui.QStackedWidget(self.mainGridWidget)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.mainmenu = QtGui.QWidget()
        self.mainmenu.setObjectName(_fromUtf8("mainmenu"))
        self.gridLayout = QtGui.QGridLayout(self.mainmenu)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.editCardsButton = QtGui.QPushButton(self.mainmenu)
        self.editCardsButton.setObjectName(_fromUtf8("editCardsButton"))
        self.gridLayout_2.addWidget(self.editCardsButton, 3, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 4, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.playButton = QtGui.QPushButton(self.mainmenu)
        self.playButton.setObjectName(_fromUtf8("playButton"))
        self.gridLayout.addWidget(self.playButton, 0, 0, 1, 2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_2 = QtGui.QLabel(self.mainmenu)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_6.addWidget(self.label_2)
        self.playerNameLineEdit = QtGui.QLineEdit(self.mainmenu)
        self.playerNameLineEdit.setObjectName(_fromUtf8("playerNameLineEdit"))
        self.horizontalLayout_6.addWidget(self.playerNameLineEdit)
        self.addPlayerButton = QtGui.QPushButton(self.mainmenu)
        self.addPlayerButton.setObjectName(_fromUtf8("addPlayerButton"))
        self.horizontalLayout_6.addWidget(self.addPlayerButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.gridLayout_11 = QtGui.QGridLayout()
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem3, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.mainmenu)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_11.addWidget(self.label, 0, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self.mainmenu)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_11.addWidget(self.pushButton, 2, 1, 1, 1)
        self.playerListWidget = QtGui.QListWidget(self.mainmenu)
        self.playerListWidget.setEditTriggers(QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.playerListWidget.setTabKeyNavigation(True)
        self.playerListWidget.setProperty("showDropIndicator", False)
        self.playerListWidget.setDragDropOverwriteMode(True)
        self.playerListWidget.setViewMode(QtGui.QListView.ListMode)
        self.playerListWidget.setUniformItemSizes(True)
        self.playerListWidget.setSelectionRectVisible(True)
        self.playerListWidget.setObjectName(_fromUtf8("playerListWidget"))
        item = QtGui.QListWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.playerListWidget.addItem(item)
        self.gridLayout_11.addWidget(self.playerListWidget, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_11)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.exitButton = QtGui.QPushButton(self.mainmenu)
        self.exitButton.setObjectName(_fromUtf8("exitButton"))
        self.horizontalLayout_5.addWidget(self.exitButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.mainmenu)
        self.playgame = QtGui.QWidget()
        self.playgame.setObjectName(_fromUtf8("playgame"))
        self.gridLayout_3 = QtGui.QGridLayout(self.playgame)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.botButtonsGridLayout = QtGui.QGridLayout()
        self.botButtonsGridLayout.setObjectName(_fromUtf8("botButtonsGridLayout"))
        self.startOverButton = QtGui.QPushButton(self.playgame)
        self.startOverButton.setObjectName(_fromUtf8("startOverButton"))
        self.botButtonsGridLayout.addWidget(self.startOverButton, 2, 0, 1, 1)
        self.goBackButton = QtGui.QPushButton(self.playgame)
        self.goBackButton.setObjectName(_fromUtf8("goBackButton"))
        self.botButtonsGridLayout.addWidget(self.goBackButton, 1, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.botButtonsGridLayout.addItem(spacerItem5, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.botButtonsGridLayout)
        self.topButtonsGridLayout = QtGui.QGridLayout()
        self.topButtonsGridLayout.setObjectName(_fromUtf8("topButtonsGridLayout"))
        self.textBrowser = QtGui.QTextBrowser(self.playgame)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.textBrowser.setPalette(palette)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.topButtonsGridLayout.addWidget(self.textBrowser, 0, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.topButtonsGridLayout.addItem(spacerItem6, 0, 0, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.scorBoardTableWidget = QtGui.QTableWidget(self.playgame)
        self.scorBoardTableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.scorBoardTableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.scorBoardTableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.scorBoardTableWidget.setObjectName(_fromUtf8("scorBoardTableWidget"))
        self.scorBoardTableWidget.setColumnCount(1)
        self.scorBoardTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.scorBoardTableWidget.setHorizontalHeaderItem(0, item)
        self.verticalLayout_4.addWidget(self.scorBoardTableWidget)
        self.topButtonsGridLayout.addLayout(self.verticalLayout_4, 0, 2, 1, 1)
        self.verticalLayout.addLayout(self.topButtonsGridLayout)
        self.playGameGridLayout = QtGui.QGridLayout()
        self.playGameGridLayout.setObjectName(_fromUtf8("playGameGridLayout"))
        self.skipButton = QtGui.QPushButton(self.playgame)
        self.skipButton.setObjectName(_fromUtf8("skipButton"))
        self.playGameGridLayout.addWidget(self.skipButton, 0, 2, 1, 1)
        self.nextButton = QtGui.QPushButton(self.playgame)
        self.nextButton.setObjectName(_fromUtf8("nextButton"))
        self.playGameGridLayout.addWidget(self.nextButton, 0, 3, 1, 1)
        self.exit2Button = QtGui.QPushButton(self.playgame)
        self.exit2Button.setObjectName(_fromUtf8("exit2Button"))
        self.playGameGridLayout.addWidget(self.exit2Button, 0, 0, 1, 1)
        self.progressBar = QtGui.QProgressBar(self.playgame)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.playGameGridLayout.addWidget(self.progressBar, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.playGameGridLayout)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.playgame)
        self.Cards = QtGui.QWidget()
        self.Cards.setObjectName(_fromUtf8("Cards"))
        self.gridLayout_14 = QtGui.QGridLayout(self.Cards)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.cardTableWidget = QtGui.QTableWidget(self.Cards)
        self.cardTableWidget.setLineWidth(1)
        self.cardTableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.cardTableWidget.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.cardTableWidget.setAlternatingRowColors(False)
        self.cardTableWidget.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.cardTableWidget.setShowGrid(True)
        self.cardTableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.cardTableWidget.setWordWrap(True)
        self.cardTableWidget.setObjectName(_fromUtf8("cardTableWidget"))
        self.cardTableWidget.setColumnCount(3)
        self.cardTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.cardTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.cardTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.cardTableWidget.setHorizontalHeaderItem(2, item)
        self.gridLayout_14.addWidget(self.cardTableWidget, 3, 0, 1, 1)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.goBack2Button = QtGui.QPushButton(self.Cards)
        self.goBack2Button.setObjectName(_fromUtf8("goBack2Button"))
        self.horizontalLayout_7.addWidget(self.goBack2Button)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.addCardButton = QtGui.QPushButton(self.Cards)
        self.addCardButton.setObjectName(_fromUtf8("addCardButton"))
        self.horizontalLayout_7.addWidget(self.addCardButton)
        self.RemoveCardButton = QtGui.QPushButton(self.Cards)
        self.RemoveCardButton.setObjectName(_fromUtf8("RemoveCardButton"))
        self.horizontalLayout_7.addWidget(self.RemoveCardButton)
        self.gridLayout_14.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.Cards)
        self.gridLayout_6.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.mainGridWidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.exit2Button, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QObject.connect(self.exitButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.editCardsButton.setText(_translate("MainWindow", "edit Cards", None))
        self.playButton.setText(_translate("MainWindow", "Play!", None))
        self.label_2.setText(_translate("MainWindow", "Player Name:", None))
        self.addPlayerButton.setText(_translate("MainWindow", "Add Player", None))
        self.label.setText(_translate("MainWindow", "Players:", None))
        self.pushButton.setText(_translate("MainWindow", "Remove Player", None))
        __sortingEnabled = self.playerListWidget.isSortingEnabled()
        self.playerListWidget.setSortingEnabled(False)
        item = self.playerListWidget.item(0)
        item.setText(_translate("MainWindow", "Player 1", None))
        self.playerListWidget.setSortingEnabled(__sortingEnabled)
        self.exitButton.setText(_translate("MainWindow", "Exit", None))
        self.startOverButton.setText(_translate("MainWindow", "Start OVer", None))
        self.goBackButton.setText(_translate("MainWindow", "Go Back", None))
        item = self.scorBoardTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Score", None))
        self.skipButton.setText(_translate("MainWindow", "Skip", None))
        self.nextButton.setText(_translate("MainWindow", "Next", None))
        self.exit2Button.setText(_translate("MainWindow", "Exit", None))
        self.cardTableWidget.setSortingEnabled(True)
        item = self.cardTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Card", None))
        item = self.cardTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Catagory", None))
        item = self.cardTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "NSFW", None))
        self.goBack2Button.setText(_translate("MainWindow", "Go Back", None))
        self.addCardButton.setText(_translate("MainWindow", "Add Card", None))
        self.RemoveCardButton.setText(_translate("MainWindow", "Remove Card", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

